using UnityEngine;

namespace Racing
{
    [RequireComponent(typeof(AudioSource))]
    public class PauseAudioSource : MonoBehaviour, IDependency<Pauser>
    {
        private new AudioSource audio;
        private Pauser pauser;
        public void Construct(Pauser obj) => pauser = obj;

        private void Start()
        {
            audio = GetComponent<AudioSource>();

            pauser.PauseStateChange += OnPauseStateChange;
        }

        private void OnDestroy()
        {
            pauser.PauseStateChange -= OnPauseStateChange;
        }

        private void OnPauseStateChange(bool isPause)
        {
            if (isPause == true)
                audio.Stop();

            if (isPause == false)
                audio.Play();
        }
    }
}
